servers:
  - http://megan-pi-iot.cfapps.io/test
  - http://katie-pi-iot.cfapps.io/test
  - http://david-pi-iot.cfapps.io/test
  - http://jpf-flask-pi-iot.cfapps.io/test
  - http://shane-pi-iot.cfapps.io/test
beers:
  - blue moon
  - killians
  - something yummy
  - banquet



